# Generated by Django 5.2.8 on 2025-12-09 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_student_id_from_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
